### ISSUE TITLE
How to version control Airbyte configuration

### ISSUE THREAD

**Issue by arimbr** [airbytehq/write-for-the-community#101]
Slack thread: https://airbytehq.slack.com/archives/C019WJFR1JT/p1633105103308000

**Comment by Popoolayemi** [comment]
Hello @arimbr I'll like to work on this topic,

I'm new here can I know the next step for the topic.

Thank you

**Comment by arimbr** [comment]
Hi @Popoolayemi thanks for your interest! This is a highly technical topic that is better suited for someone who has actually done this before. Did you check the Slack thread to get more context? If you are familiar with Airbyte, then, can you share a couple of sentences about how you would actually implement this?
