### ISSUE TITLE
Replicate Salesforce and Zendesk data to Keen for unified analytics

### ISSUE THREAD

**Issue by arimbr** [airbytehq/write-for-the-community#102]
Distribute:
- [ ] [Airbyte recipes](https://airbyte.io/recipes/salesforce-zendesk-analytics)

**Comment by arimbr** [comment]
Draft: https://docs.google.com/document/d/1NDEnfV6MQq6YNVU4aRaGz5VMkKPAvgD-KP4IKeRD9CI/edit?usp=sharing

**Comment by GlennRossman** [comment]
Evaluated article for byline contributed article - not appropriate

**Comment by johnlafleur** [comment]
Published on: https://airbyte.io/recipes/salesforce-zendesk-analytics
