### ISSUE TITLE
Use Airbyte API to manage connections programmatically

### ISSUE THREAD

**Issue by arimbr** [airbytehq/write-for-the-community#113]

**Comment by arimbr** [comment]
Draft: https://docs.google.com/document/d/1uX7ysAUYaGxYtaeEvrx4jtUgIxQQczgn52e5yFdHPdw/edit

**Comment by prasrvenkat** [comment]
Is this still being written? If not let me know if I can write something up.

**Comment by arimbr** [comment]
@prasrvenkat Cool! I think this is on hold! Have you tried to do this with Airbyte before?

Ideally we are looking for Airbyte users that have already done something like this with their own deployment. :)

**Comment by prasrvenkat** [comment]
> @prasrvenkat Cool! I think this is on hold! Have you tried to do this with Airbyte before?
> 
> Ideally we are looking for Airbyte users that have already done something like this with their own deployment. :)

Yeah we are using it in our GKE infrastructure and onboard these through API from our application.

**Comment by arimbr** [comment]
@prasrvenkat That's awesome! Can you book some time with me to discuss the outline and process?
https://calendly.com/ari-airbyte/30min

Looking forward!
