### ISSUE TITLE
Load data from Google Sheets to BigQuery

### ISSUE THREAD

**Issue by arimbr** [airbytehq/write-for-the-community#117]

**Comment by arimbr** [comment]
Draft: https://docs.google.com/document/d/1OyPXDkauSrOrQgF1cMvMUVYOhJiEHYdtYjpx62y_TOs/edit#

**Comment by fabform** [comment]
Handy to get the google sheets id
[how to get google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)
