### ISSUE TITLE
Saving costs and maximizing data engineering procedures using Airbyte

### ISSUE THREAD

**Issue by xTrilton** [airbytehq/write-for-the-community#129]
# Saving costs and maximizing data engineering procedures using Airbyte

In this tutorial, you will learn how to maximize data engineering processes using Airbyte and also eliminate the challenges brought by in-house connectors by using Airbyte custom connectors.

# What we will cover in this article:

## The downsides of creating your own connector

In this section, we will explore how building your own connector is expensive and hard. We will cover the following points:

* In-hose connectors that are  are expensive and take more effort to maintain
* Creating a custom connector takes a lot of time and expertise.

## How Airbyte helps you save money and time

This segment will show you how to use Airbyte to reduce costs when using connectors and carry out data migration effectively using Airbyte. We will cover the following points and Airbyte features use cases:

* Airbyte gives you real-time monitoring and debugging tools which help you identify and eliminate errors.
* Migrating your data to your preferred destination using customized Airbyte connectors 
* Airbyte gives you connector management tools and also integrates with more than 100 connectors.

**Comment by arimbr** [comment]
Closing as arguments already covered here: https://airbyte.com/blog/etl-framework-vs-etl-script
