### ISSUE TITLE
Airbyte and the state of data integration/engineering

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/write-for-the-community#19]

**Comment by avaidyanatha** [comment]
This could be a good general blog postl; I think this would go along well with a "State of data engineering" landscape style post like this: https://lakefs.io/the-state-of-data-engineering-in-2021/

**Comment by Opiano1** [comment]
I will love to write on this

**Comment by avaidyanatha** [comment]
@Opiano1 Awesome, it's yours! Let me know if you want to meet up to go over an outline. Otherwise, let me know when you have a draft going :)

**Comment by Opiano1** [comment]
Alright. 

Sure, we can go over an outline or you can share if you have a proposed outline to be covered in the intended article.

**Comment by Opiano1** [comment]
@avaidyanatha 

Kindly see the first draft here for your perusal and comments

https://docs.google.com/document/d/1xCl1cUxiK1MUXHvHJvB4MsV-rdFO9I9JUMcowz5M9Sc/edit?usp=sharing

**Comment by avaidyanatha** [comment]
@Opiano1 I have left 2 high level comments before I start editing further - if we could get through those, this will be a very valuable piece!

**Comment by Opiano1** [comment]
@avaidyanatha 

I've updated the document base on your request:

https://docs.google.com/document/d/1xCl1cUxiK1MUXHvHJvB4MsV-rdFO9I9JUMcowz5M9Sc/edit?usp=sharing

Looking forward to hearing from you

**Comment by avaidyanatha** [comment]
@Opiano1 Hey! Thank you for updating the doc, I'll be passing this off to our content strategist @arimbr to push this to the finish line!

**Comment by Opiano1** [comment]
@avaidyanatha 

Great thank you for the update. 

@arimbr 

I look forward to your review and feedback. 

Thank you
