### ISSUE TITLE
[VIDEO] CDK Walkthrough/Tutorial

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/write-for-the-community#34]
Convert this written tutorial into a video, and post the video on top of the tutorial
https://docs.airbyte.io/tutorials/toy-connector

**Comment by sherifnada** [comment]
@johnlafleur I worry that "porting" this tutorial into video format without making it much shorter/higher level would result in a video that goes out of date very frequently and would be hard to maintain. Instead, WDYT about making a video describing the process, but without necessarily implementing it?

**Comment by johnlafleur** [comment]
LGTM
Wdyt @michel-tricot ?

**Comment by michel-tricot** [comment]
LGTM as well

**Comment by avaidyanatha** [comment]
Let's convert this to a CDK video, I think that will be very effective.
