### ISSUE TITLE
[TOPIC] How to forecast your purchase orders on Shopify using Airbyte and MindsDB

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/write-for-the-community#38]
This is a tutorial on which we will collaborate on with the MindsDB team. The agreement we reached is that we write the 1st part of the tutorial about: how to replicate data from Shopify to a Postgres database to save store info. 

The MindsDB team will write about using MindsDB Ai Tables to train the model that will forecast the purchase order.

**Comment by DominusKelvin** [comment]
@johnlafleur I am ready to take this on
