### ISSUE TITLE
How open-source can help you scrape LinkedIn in a Postgres database (using BeautifulSoup + Airbyte)

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/write-for-the-community#41]
- Set up BeautifulSoup
- Take a LinkedIn profile page
- Scrape that data and export in a JSON
- Set up Airflow and use Airflow to trigger a data integration of the JSON files to a Postgres database using Airbyte's API
- User in the end should be able to input a csv of LinkedIn Profile URLs

**PROMOTION TO DO**
- [x] Towards Data Science / Medium - by @johnlafleur 
- [x] dev.to - by @johnlafleur
- [x] Hackernoon - by @johnlafleur 
- [x] Dzone - by @johnlafleur

**Comment by DominusKelvin** [comment]
This as well :)
