### ISSUE TITLE
Installing Airbyte on MacOS/Linux/Windows

### ISSUE THREAD

**Issue by mandulamadhu143210** [airbytehq/write-for-the-community#43]

**Comment by DominusKelvin** [comment]
@johnlafleur can I take this on?

**Comment by johnlafleur** [comment]
@avaidyanatha is now owning content production. I let him reply :)

**Comment by avaidyanatha** [comment]
@DominusKelvin Absolutely, let's set up some time to spec this out.

**Comment by DominusKelvin** [comment]
> @DominusKelvin Absolutely, let's set up some time to spec this out.

okay @avaidyanatha when would you want us to start?

**Comment by Emidowojo** [comment]
Hello, can I work on this project please?

**Comment by arimbr** [comment]
Closing this, as this better suited for the docs and not the blog.
