### ISSUE TITLE
[TOPIC] K8s - Wrapping Docker Image at Runtime

### ISSUE THREAD

**Issue by cgardens** [airbytehq/write-for-the-community#51]
Would love to see a blogpost explaining what we're doing with K8s (needing to "wrap" a docker image at runtime in K8s; sidecar + socat). @davinchia @jrhizor . It seems like what we're doing here isn't super common, so it could be a cool go to article for people in similar situations.

**Comment by arimbr** [comment]
This is done and covered in two articles in our engineering blog:
- https://airbyte.com/blog/extending-docker-images-on-kubernetes
- https://airbyte.com/blog/scaling-data-pipelines-kubernetes
