### ISSUE TITLE
[TOPIC] Migrate to Cloud Database To Reduce Costs

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/write-for-the-community#57]
Sources: Aurora MySQL, MongoDB, SQL Server
Destination: Snowflake
Business Intelligence Tool: Microsoft Power BI & others

Topics:
* Decommission Legacy Platforms and Migrate From On-Prem to the Cloud
* Quicker Troubleshooting & Reporting

Inspiration: https://fivetran.com/case-studies/case-study-copyright

**Comment by GeoSegun** [comment]
Hi, I would like to work on this topic

can I send an outline to get started?
