### ISSUE TITLE
Maximise the Value of Your Salesforce Data

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/write-for-the-community#66]
Inspiration: https://fivetran.com/blog/how-to-maximise-the-value-of-your-salesforce-data

**Comment by arimbr** [comment]
Draft: https://docs.google.com/document/d/1MnP3BrTkyBNOLNyLrYmGFbkksjIYKQ0UWftOnwUqkRU/edit?usp=sharing

**Comment by johnlafleur** [comment]
The goal was to show in each point how you can leverage Airbyte to make the most of Salesforce data...
None of the 5 steps make use of Airbyte. 

Also you want the paragraph title to be self-explanatory, so a reader can understand what it is about, and read only the sections that make sense to them....as in the article mentioned as inspiration.

As is, this article can't be leveraged at all.

**Comment by arimbr** [comment]
@johnlafleur Thanks for checking that out! I totally agree with you. The example article from Fivetran does give concrete examples of how to use Fivetran for Salesforce data.

At the same time, I feel like we need to be more explicit about what we expect from an article. Unfortunately, a title and an inspiration article don't seem to be enough.
