### ISSUE TITLE
Build a single customer view with open-source tools

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/write-for-the-community#68]
Distribute:
- [x] [Airbyte website](https://airbyte.io/recipes/single-customer-view)
- [x] [Linkedin](https://www.linkedin.com/posts/tuanchris_build-a-single-customer-view-with-open-source-activity-6867043040230567936-w-kQ)
- [x] Reddit [r/dataanalysis](https://www.reddit.com/r/dataanalysis/comments/qwsf0s/build_a_single_customer_view_with_opensource_tools/)
- [x] Hacker News
- [x] [Airbyte Slack](https://airbytehq.slack.com/archives/C01AB7G87NE/p1637250904086200)

**Comment by arimbr** [comment]
@johnlafleur I changed the title of the article to rank on "customer journey analytics" as this a highly searched term (1,1k searches/month) with low difficulty on Google. On the Fivetran article you mentioned, they also use the "customer journey" term but use "360-degree view" which doesn't help to rank for any keyword.

Then, I thought that something like "Customer journey analytics with open source tools" would be a good title to tank on Google for "customer journey analytics"...
