### ISSUE TITLE
Need Airbyte Tutorial

### ISSUE THREAD

**Issue by prolayghosh1978** [airbytehq/write-for-the-community#70]
Hi,
I am Prolay Ghosh from EY GDS. I am the Practice Lead of Data Management. I am trying to learn Airbyte and wants to introduce to my leadership team in case we can take it to customer in our proposal,

Thanks why I need Airbyte Tutorial.

Requesting you to share.

Thanks ,
Prolay Ghosh
Sr. Manager - EY
Mobile - +91 9830302226

**Comment by avaidyanatha** [comment]
@prolayghosh1978 Have you checked out our documentation? https://docs.airbyte.io/
