### ISSUE TITLE
How OSS companies changed in the last few years

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/write-for-the-community#74]
Yesterday, I had some discussions with another open-source founder and he listed quite a few good points about how OSS companies of today are different from the previous decades:
1. Today companies are started with the OSS project and not many years after the project existed 
2. They are created with an intention of sustainability and revenue generation. Developer users also want an OSS company to have revenue, unlike the fanatic developers of the past
3. The products are generally aimed at companies instead of individuals
4. Faster product improvement than in the past(because OSS projects used to be side projects). Also we aren't waiting around for contributors to volunteer, instead we are moving ahead to do the right things
5. Users have access to cloud hosting and APIs, so ease of getting started is 100x better than before
6. Real focus on design and UX. Well-designed OSS used to be an oxymoron, not today

I think that's very true :slightly_smiling_face: 

Inspiration to use:
https://www.techrepublic.com/article/the-open-source-decade-fueled-by-cloud-and-github/
https://www.zdnet.com/article/open-source-turns-20/
https://www.consortiuminfo.org/open-source-open-standards/a-brief-history-of-open-source-software/

**Comment by avaidyanatha** [comment]
Inspiration to use:
https://www.techrepublic.com/article/the-open-source-decade-fueled-by-cloud-and-github/
https://www.zdnet.com/article/open-source-turns-20/

**Comment by arimbr** [comment]
Draft: https://docs.google.com/document/d/13hM7ifUFFPG9jv7jOUFmbrHV1VB0JP-EATbmoRYtedY/edit

**Comment by johnlafleur** [comment]
I don't see the link between the draft and the initial outline. I don't see any of the points made in the outline in the draft. 
The point of this article that OSS companies have changed in the past 2-3 years from these 6 points mentioned. 

Some examples of such new-generation OSS companies:
* Airbyte
* Posthog
* Preset
* dbt
* Appsmith
* Papercups
* QuestDB

Here was the original outline: https://docs.google.com/document/d/1vCC-SPOgVMNfmff_egilV01-3te8MWi-gUwThIkvqVw/edit

**Comment by arimbr** [comment]
@johnlafleur Totally agree! The article does not reference the OSS companies included in the outline. Instead, it references some general open source projects (not companies) like Linux, Firefox, Python, and GIMP.

They changed the title from "How Open-Source Companies Have Changed In The Last Decade" to "How Open Source Software Has Evolved" :/

I will check with Content Turbine to see what happened here...

I like your outline and see the value that could from there!
