### ISSUE TITLE
Set up a modern data stack with Docker

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/write-for-the-community#78]
A reader should be able to spin up Airbyte, dbt, Bigquery, and Superset in 10 minutes. 

This can be inspired from a collaboration that we did here: https://towardsdatascience.com/bootstrap-a-modern-data-stack-in-5-minutes-with-terraform-32342ee10e79

We'd like to replace Metabase with Superset, as we find it generally better to use.

**Comment by arimbr** [comment]
Draft: https://docs.google.com/document/d/1NaskVHCtLjA2NMF7xMSiWnLdl6pVAUwM4C12DKmE5pY/edit

**Comment by GlennRossman** [comment]
Evaluated article for byline contributed article - not appropriate
