### ISSUE TITLE
Measure your true Customer Acquisition Costs

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/write-for-the-community#80]
We have a swath of Marketing/Customer Success [sources](https://airbyte.io/sources) and it would be cool to bring data from across all of them to calculate the true CAC of a customer. 

Some sources to consider:
- Salesforce
- HubSpot
- Google Ads
- Zendesk

**Comment by DraftKieran** [comment]
Draft.dev Link: https://docs.google.com/document/d/1hmpEoKevPSb0fTCcHN4WgZc3dxdPd6zf9wjvzAVfZco/edit#heading=h.rqyhntmp4ccd

**Comment by GlennRossman** [comment]
Evaluated article for byline contributed article - not appropriate

I like the concept and it starts out well but then gets very technical (and code-y) which makes it less acceptable.
