### ISSUE TITLE
Track changes in data with Change Data Capture (CDC)

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/write-for-the-community#81]
We want an article going over the usage of the CDC feature in Airbyte. We want to go over the use of CDC for Postgres, MySQL, and MSSQL.

Here are resources for this piece:
https://docs.airbyte.io/understanding-airbyte/cdc
https://www.youtube.com/watch?v=NMODvLgZvuE&t=10s&ab_channel=Airbyte
https://docs.airbyte.io/integrations/sources/mysql#change-data-capture-cdc
https://docs.airbyte.io/integrations/sources/postgres#change-data-capture-cdc-logical-replication-wal-replication
https://docs.airbyte.io/integrations/sources/mssql#change-data-capture-cdc

The outline should resemble this:

1. CDC overview
  a. Why is CDC importatnt? What is the context behind it?
  b. Is using CDC the right decision for me?
2. Prerequisites 
3. Setting up CDC for MySQL 
  a. Go through first sync
  b. Create and delete data before the next sync
  c. Show that CDC captures the change
  d. Repeat these steps for PostgreSQL and MSSQL
4. Setting up CDC for PostgreSQL
5. Setting up CDC for MSSQL
6. Wrapping up.

**Comment by arimbr** [comment]
Draft: https://docs.google.com/document/d/1Fd5wnA6a6DJuGBD7KO_xychrrTEwL37zAIJibESioSE/edit

**Comment by arimbr** [comment]
We decided to split this long article into three others to cover CDC for MySQL, PostgreSQL, and Mirosoft SQL Server separately.

https://github.com/airbytehq/write-for-the-community/issues/92
https://github.com/airbytehq/write-for-the-community/issues/93
https://github.com/airbytehq/write-for-the-community/issues/94
