### ISSUE TITLE
Replicate your Production MySQL database to a Test Environment

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/write-for-the-community#83]
## Main Issue

Often times, users will want to clone their production database so that they can test changes on it or if they want to use real data for in house analytics. This process can be easily done with Airbyte, so we want a recipe that tackles that concept.

We can use Postgres and MySQL for this, and highlight quirks that might occur in either one.

**Comment by avaidyanatha** [comment]
Some points that we should cover:

Why replicate your production database?
- Replicating your production data is good practice
- Testing on production data gives us a more accurate picture for replicating production bugs
- Testing with production data guarantees proper volume for simulating actions
- Data volume increases the likelihood of edge cases

- Consider other tools? Why use Airbyte?

**Comment by arimbr** [comment]
Draft: https://docs.google.com/document/d/1NbSba8qe9V6YLN-yEYy8MuP7xwO2EXxhH45qgoY2kgU/edit?usp=sharing

**Comment by GlennRossman** [comment]
Evaluated article for byline contributed article - not appropriate
