### ISSUE TITLE
ETL vs ELT pipelines: Which one to choose?

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/write-for-the-community#85]
Audience: Data Engineers

SEO keywords: etl vs elt, etl pipeline, etl data pipeline, elt pipeline, elt data pipeline

Outline:
- Introduction to Data pipelines 
  - Define ETL
  - Define ELT
  - Why choose one or the other?
- ETL/ELT use cases
- EL(T) pipelines with Airbyte Cloud

Inspiration:
https://www.snowflake.com/guides/etl-pipeline
https://www.xplenty.com/blog/etl-vs-elt/
https://databricks.com/glossary/extract-transform-load
https://www.qlik.com/us/etl/etl-pipeline

**Comment by arimbr** [comment]
Draft: https://docs.google.com/document/d/15TIPOWBQeb6TmaqGx4Vh-lT2qSn7tjPcwFV3ccD1p3s/edit?usp=sharing
