### ISSUE TITLE
What is data replication? Use cases and challenges for data teams

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/write-for-the-community#86]
Audience: Data Engineers, Data Analysts

SEO keywords: data replication, what is data replication, database replication, data replication strategies, data replication tools

Outline: 
- What is data replication
- Difference with database replication
- Why do data teams replicate data
  - Centralize data 
  - Different usages: analytical queries vs operational queries
  - Isolating different environments: local, testing, production
  - Data Archiving
- Data replication strategies
- Data replication challenges (CDC, ...)
- How Airbyte commoditized data replication

Inspiration:
https://www.stitchdata.com/resources/data-replication/
https://hevodata.com/learn/data-replication-strategy/

**Comment by arimbr** [comment]
Draft: https://docs.google.com/document/d/1KxrpNu5Ny9rgnJrlLH4toECMvYUnuJKLDXNAW505ZDM/edit?usp=sharing

**Comment by arimbr** [comment]
New Draft: https://docs.google.com/document/d/1DPJXJaVyYTQvssIQHmTLXObqAyNXZcFREGYF1x5XfsE/edit?usp=sharing
