### ISSUE TITLE
Evaluate Your Google Ads Performance with Airbyte and Metabase

### ISSUE THREAD

**Issue by arimbr** [airbytehq/write-for-the-community#89]
It's important that Google Ads users understand how their advertising spend is linked to results over time. In this tutorial, you’ll show developers how to set up a dashboard to view Google Ads data (provided by us) using Metabase and Airbyte.

**Comment by arimbr** [comment]
Draft: https://docs.google.com/document/d/1cbmozUa2fanUoVicybdmUyL8Lw-HmrNLy6RZ5UozucM/edit?usp=drivesdk

**Comment by DraftKieran** [comment]
Updated draft: https://docs.google.com/document/d/1oBWa05n21PQjEDk4TFIvMkGeZYVXSszNEli_0eIwO_I/edit#heading=h.xkdic8g3cmw
